'use strict';

// tests for createPeople
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createPeople', '/controllers/peopleController.js', 'createPeople');

describe('createPeople', () => {
    before((done) => {
        done();
    });

    it('Creando un registro en la tabla People', async() => {
        const response = await wrapped.run({
            pathParameters: { number: '14' }
        });

        let id = JSON.parse(response.body).id;
        if (id === undefined) {
            expect(response.statusCode).equal(200);
        } else {
            expect(response.statusCode).equal(201);
        }
        expect(response.body.id).to.not.be.empty;
    }).timeout(10000);
});