'use strict';

// tests for getAllPlanets
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getAllPlanets', '/controllers/planetController.js', 'getAllPlanets');

describe('getAllPlanets', () => {
    before((done) => {
        done();
    });

    it('Obtener los datos del endpoint getAllPlanets', async() => {
        const response = await wrapped.run({});
        expect(response.statusCode).to.equal(200);
    });
});