'use strict';

// tests for getAllPeople
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getAllPeople', '/controllers/peopleController.js', 'getAllPeople');

describe('getAllPeople', () => {
    before((done) => {
        done();
    });

    it('Obtener los datos del endpoint getAllPeople', async() => {
        const response = await wrapped.run({});
        expect(response.statusCode).to.equal(200);
    });
});