'use strict';

// tests for updatePlanet
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('updatePlanet', '/controllers/planetController.js', 'updatePlanet');

describe('updatePlanet', () => {
    before((done) => {
        done();
    });

    it('Actualizar un registro del endpoint updatePlanet', async() => {
        const response = await wrapped.run({
            pathParameters: { id: '8' },
            body: JSON.stringify({
                paramName: 'Kripton',
                paramValue: 'Kriptoniano'
            })
        });
        expect(response.statusCode).equal(200);
        expect(response.body).to.not.be.empty;
        expect(JSON.parse(response.body).message).equal("Actualizado con éxito");
    });
});