'use strict';

// tests for updatePeople
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('updatePeople', '/controllers/peopleController.js', 'updatePeople');

describe('updatePeople', () => {
    before((done) => {
        done();
    });

    it('Actualizar un registro del endpoint updatePeople', async() => {
        const response = await wrapped.run({
            pathParameters: { id: '8' },
            body: JSON.stringify({
                paramName: 'paramName',
                paramValue: 'paramValue'
            })
        });
        expect(response.statusCode).equal(200);
        expect(response.body).to.not.be.empty;
        expect(JSON.parse(response.body).message).equal("Actualizado con éxito");
    });
});